# Generated by Django 4.2 on 2023-04-28 04:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('objective', models.CharField(max_length=511)),
                ('generation_progress_percent', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('questions_text', models.TextField(blank=True, null=True)),
                ('guide_text', models.TextField(blank=True, null=True)),
                ('tasks_list_js_array', models.TextField(blank=True, null=True)),
                ('tasks_list_text', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1023, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team')),
            ],
        ),
    ]
