# Generated by Django 4.2 on 2023-04-29 20:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_role_name_team_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
