# Generated by Django 4.2 on 2023-04-29 20:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_team_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
