# Generated by Django 4.2 on 2023-04-30 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_alter_team_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
