# Generated by Django 4.2 on 2023-04-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_team_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='tokens_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
