# Generated by Django 4.2 on 2023-05-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='ai_prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
