# Generated by Django 4.2 on 2023-05-02 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0009_role_ai_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='latest_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
