# Generated by Django 4.2 on 2023-05-02 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0010_chat_latest_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='latest_summary',
            new_name='log_historical',
        ),
    ]
