# Generated by Django 4.2 on 2023-05-05 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0011_rename_latest_summary_chat_log_historical'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='moderator_image_url',
            field=models.URLField(blank=True, max_length=1023, null=True),
        ),
    ]
