# Generated by Django 4.2 on 2023-05-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0012_team_moderator_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_speaker_name',
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
    ]
