# Generated by Django 4.2 on 2023-05-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0013_chat_last_speaker_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='last_speaker_name',
        ),
        migrations.AddField(
            model_name='chat',
            name='next_speaker_name',
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
    ]
